#!/bin/bash
export HOLBERTON="Betty"
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	../0-alias
	../0-hello_world
	../0-iam_betty
	../0x02-shell_redirections/0-alias
	../2-hellofile

nothing added to commit but untracked files present (use "git add" to track)
